#!/bin/sh
#
# Test driver
# 
# Environment variables
#   SELECT: glob used to select tests to run (default is *)
#   DEBUG: if set and non-empty, adds --debug to pp
#

PP=./pp
TMPDIR=/tmp/pp.test

#d=${1%/*}
#NAME=${1#$d/}
d=`dirname $1`
NAME=`basename $1`
DESC="** NO DESCRIPTION **"

desc () { DESC="$*"; }

pass () { echo "PASS $NAME: $DESC"; exit 0; }
fail () { echo "FAIL $NAME: $DESC";
          test $# -gt 0 && echo "       reason: $*"; 
          exit 1; }
skip () { echo "?    $NAME"; exit 0; }

#-- invokes the front-end only of pp
pp_front_end () {
    $PP --platform=null \
        --wrkdir=$TMPDIR \
	--only-front \
        ${DEBUG:+--debug} \
        --no-clean \
        ${1+"$@"} \
    || fail
}

eval "case \$NAME in ${SELECT:-*}) :;; *) skip;; esac"

rm -rf $TMPDIR
mkdir $TMPDIR

. "$1"
fail
