#!/bin/sh

desc 'test %{} and %() expansion'

pp_front_end - foo=FOO bar=BAR<<.
        %post
        : t-1=%{foo}
        : t-2=%(echo \$bar | tr A K)
        : t-3=%{foo} %{foo} %{foo} bar
.

grep 't-1=FOO' $TMPDIR/%post.run > /dev/null || fail "t-1 grep failed"
grep 't-2=BKR' $TMPDIR/%post.run > /dev/null || fail "t-2 grep failed"
grep 't-3=FOO FOO FOO bar' $TMPDIR/%post.run >/dev/null || 
    fail "t-3 grep failed"

pass
